// src/routes/year/+page.svelte
<script lang="ts">
    let msPassed = $state(0);
    let msTotal = $state(0);
    let percentage = $state(0);
    let currentYear = $state(0);

    const updateTimeMetrics = () => {
        const currentDate = new Date();
        const year = currentDate.getFullYear();

        if (currentYear !== 0 && year !== currentYear) {
            currentYear = year;
            msPassed = 0;
            msTotal = 0;
            percentage = 0;
        } else {
            currentYear = year;
        }

        const startOfYear = new Date(year, 0, 1);
        const endOfYear = new Date(year + 1, 0, 1);

        msPassed = currentDate.getTime() - startOfYear.getTime();
        msTotal = endOfYear.getTime() - startOfYear.getTime();
        percentage = (msPassed / msTotal) * 100;
    };

    $effect(() => {
        updateTimeMetrics();
        const intervalId = setInterval(updateTimeMetrics, 16);
        return () => clearInterval(intervalId);
    });
</script>

<main class={`relative h-dvh w-dvw grid place-items-center`}>
    <div class={`bg-yellow-100 md:px-14 p-6 rounded-md`}>
        <p class={`md:text-xl text-lg`}>
            The year is
            {percentage ? percentage.toFixed(14) : "----------"}
            % over
        </p>
    </div>
</main>

// app/year/page.jsx
"use client";
import { useEffect, useState } from "react"

export default function Year() {
  
  const [msPassed, setMsPassed] = useState(null);
  const [msTotal, setMsTotal] = useState(null);
  const [percentage, setPercentage] = useState(null);

  useEffect(() => {
    const currentYear = new Date().getFullYear();

    const currentDate = new Date();
    const startOfYear = new Date(currentYear, 0, 1);
    setMsPassed(currentDate - startOfYear);

    const nextYear = currentYear + 1;
    const endOfYear = new Date(nextYear, 0, 1);
    setMsTotal(endOfYear - startOfYear);
  }, [])

  useEffect(() => {
    const updateIntervalMs = 1;
    const intervalId = setInterval(() => {
      setPercentage((msPassed / msTotal) * 100)
      setMsPassed(prev => prev + updateIntervalMs);
    }, updateIntervalMs)
    return () => clearInterval(intervalId);
  }, [msPassed, msTotal])

  return (
    <main>
      <div className={`w-screen h-screen flex flex-col md:flex-row justify-center items-center gap-2 text-xl`}>
        <p>The year is</p>
        <p className={`${percentage ? "text-left" : "text-center"} w-[200px]`}>{(percentage) ? percentage : "----------"}</p>
        <p>% over</p>
      </div>  
    </main>
  )    
}
